 version: 2
 jobs:   
   three:
     docker:
       - image: circleci/ruby:2.4.1
     working_directory: /tmp
     steps:
       - run: 
          name: Compress Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artfact-2;
            zip -r myartifact.zip /tmp
       - store_artifacts:
          path: myartifact.zip
          
 workflows:
  version: 2
  one_and_two:
   jobs:
    - three
    
       
 
