 version: 2
 jobs:
   one:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
       - run: mkdir -p my_workspace
       - run: echo "Trying out workspaces" > my_workspace/echo-output
       - persist_to_workspace:
          # must be an absolute path, or relative path from working_directory
          root: my_workspace
          # must be relative path from root
          paths: 
           - echo-output
   two:
     docker:
       - image: circleci/ruby:2.4.1
     working_directory: /tmp
     steps:
       - run: 
        name: Creating Dummy Artifacts
        command: |
         echo "my artifact file" > /tmp/artifact-1;
         mkdir /tmp/artifacts;
         echo "my artifact files in a dir" > /tmp/artifacts/artfact-2;
       - store_artifacts:
        path: /tmp/artifact-1
        destination: artifact-file
        
       - store_artifacts:
        path: /tmp/artifacts
          
 workflows:
  version: 2
  one_and_two:
   jobs:
    - one
    - two:
       requires:
        - one
       
 
